const sourceCatalog = [
  {
    sourceKey: 'openai-news',
    name: 'OpenAI News',
    feedUrl: 'https://openai.com/news/rss.xml',
    homepageUrl: 'https://openai.com/news/',
    feedType: 'rss',
    dailyLimit: 2,
    trustScore: 20,
  },
  {
    sourceKey: 'google-ai',
    name: 'Google AI',
    feedUrl: 'https://blog.google/technology/ai/rss/',
    homepageUrl: 'https://blog.google/technology/ai/',
    feedType: 'rss',
    dailyLimit: 2,
    trustScore: 20,
  },
  {
    sourceKey: 'github-ai-ml',
    name: 'GitHub AI & ML',
    feedUrl: 'https://github.blog/ai-and-ml/feed/',
    homepageUrl: 'https://github.blog/ai-and-ml/',
    feedType: 'rss',
    dailyLimit: 1,
    trustScore: 18,
  },
  {
    sourceKey: 'hugging-face-blog',
    name: 'Hugging Face Blog',
    feedUrl: 'https://huggingface.co/blog/feed.xml',
    homepageUrl: 'https://huggingface.co/blog',
    feedType: 'rss',
    dailyLimit: 2,
    trustScore: 19,
  },
  {
    sourceKey: 'microsoft-ai',
    name: 'Microsoft AI',
    feedUrl: 'https://www.microsoft.com/en-us/ai/blog/feed/',
    homepageUrl: 'https://www.microsoft.com/en-us/ai/blog/',
    feedType: 'rss',
    dailyLimit: 1,
    trustScore: 19,
  },
  {
    sourceKey: 'nvidia-generative-ai',
    name: 'NVIDIA Generative AI',
    feedUrl: 'https://blogs.nvidia.com/blog/category/generative-ai/feed/',
    homepageUrl: 'https://blogs.nvidia.com/blog/category/generative-ai/',
    feedType: 'rss',
    dailyLimit: 1,
    trustScore: 18,
  },
  {
    sourceKey: 'aws-machine-learning',
    name: 'AWS Machine Learning Blog',
    feedUrl: 'https://aws.amazon.com/blogs/machine-learning/feed/',
    homepageUrl: 'https://aws.amazon.com/blogs/machine-learning/',
    feedType: 'rss',
    dailyLimit: 1,
    trustScore: 17,
  },
  {
    sourceKey: 'arxiv-cs-ai',
    name: 'arXiv cs.AI',
    feedUrl: 'https://rss.arxiv.org/rss/cs.AI',
    homepageUrl: 'https://arxiv.org/list/cs.AI/recent',
    feedType: 'rss',
    dailyLimit: 2,
    trustScore: 16,
  },
  {
    sourceKey: 'arxiv-cs-lg',
    name: 'arXiv cs.LG',
    feedUrl: 'https://rss.arxiv.org/rss/cs.LG',
    homepageUrl: 'https://arxiv.org/list/cs.LG/recent',
    feedType: 'rss',
    dailyLimit: 2,
    trustScore: 16,
  },
].map((source) =>
  Object.freeze({
    ...source,
    contentMode: 'summary',
    licenseCode: 'link-only',
    enabled: true,
  }),
);

module.exports = Object.freeze(sourceCatalog);
