const MAX_IMAGE_BATCH_COUNT = 20;
const MAX_IMAGE_FILE_SIZE_MB = 20;
const MAX_IMAGE_FILE_SIZE = MAX_IMAGE_FILE_SIZE_MB * 1024 * 1024;

const MAX_VIDEO_FILE_SIZE_MB = 20;
const MAX_VIDEO_FILE_SIZE = MAX_VIDEO_FILE_SIZE_MB * 1024 * 1024;

const MAX_ARTICLE_VIDEO_COUNT = 2;

const IMAGE_TYPE_LIMIT_MESSAGE = '只能上传图片文件';
const IMAGE_SIZE_LIMIT_MESSAGE = `图片大小不能超过 ${MAX_IMAGE_FILE_SIZE_MB}MB`;
const IMAGE_BATCH_COUNT_LIMIT_MESSAGE = `单次最多只能上传 ${MAX_IMAGE_BATCH_COUNT} 张图片`;
const VIDEO_TYPE_LIMIT_MESSAGE = '只能上传视频文件';
const VIDEO_SIZE_LIMIT_MESSAGE = `视频大小不能超过 ${MAX_VIDEO_FILE_SIZE_MB}MB`;
const VIDEO_COUNT_LIMIT_MESSAGE = `每篇文章最多只能上传 ${MAX_ARTICLE_VIDEO_COUNT} 个视频`;

module.exports = {
  MAX_IMAGE_BATCH_COUNT,
  MAX_IMAGE_FILE_SIZE_MB,
  MAX_IMAGE_FILE_SIZE,
  MAX_VIDEO_FILE_SIZE_MB,
  MAX_VIDEO_FILE_SIZE,
  MAX_ARTICLE_VIDEO_COUNT,
  IMAGE_TYPE_LIMIT_MESSAGE,
  IMAGE_SIZE_LIMIT_MESSAGE,
  IMAGE_BATCH_COUNT_LIMIT_MESSAGE,
  VIDEO_TYPE_LIMIT_MESSAGE,
  VIDEO_SIZE_LIMIT_MESSAGE,
  VIDEO_COUNT_LIMIT_MESSAGE,
};
