-- PostgreSQL stage 1 schema for coderx.
-- Run this after creating the target PostgreSQL database named `coderx`.
-- This file keeps table and column names as close to MySQL as possible.
-- PostgreSQL requires quoting the table name public."user" in all future SQL.
-- Import legacy MySQL DATETIME values with an explicit session TimeZone.

BEGIN;

CREATE TABLE IF NOT EXISTS public."user" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(name) <= 30),
  password text CHECK (length(password) <= 255),
  status integer DEFAULT 0,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  google_id text CHECK (length(google_id) <= 255),
  oauth_provider text CHECK (length(oauth_provider) <= 50),
  github_id text CHECK (length(github_id) <= 255),
  CONSTRAINT user_name_key UNIQUE (name),
  CONSTRAINT user_google_id_key UNIQUE (google_id),
  CONSTRAINT user_github_id_key UNIQUE (github_id)
);

CREATE TABLE IF NOT EXISTS public.tag (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(name) <= 10),
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT tag_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.article (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  title text NOT NULL CHECK (length(title) <= 50),
  content text,
  views bigint DEFAULT 0 CHECK (views >= 0),
  status integer DEFAULT 0,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT article_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.collect (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text NOT NULL CHECK (length(name) <= 30),
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT collect_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.avatar (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  filename text NOT NULL CHECK (length(filename) <= 255),
  mimetype text CHECK (length(mimetype) <= 30),
  size integer,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT avatar_filename_key UNIQUE (filename),
  CONSTRAINT avatar_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.profile (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  avatar_url text CHECK (length(avatar_url) <= 200),
  age integer,
  sex text CHECK (length(sex) <= 2),
  phone text CHECK (length(phone) <= 30),
  email text CHECK (length(email) <= 30),
  career text CHECK (length(career) <= 30),
  address text CHECK (length(address) <= 30),
  sign text CHECK (length(sign) <= 30),
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT profile_user_id_key UNIQUE (user_id),
  CONSTRAINT profile_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.article_collect (
  article_id bigint NOT NULL,
  collect_id bigint NOT NULL,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  PRIMARY KEY (article_id, collect_id),
  CONSTRAINT article_collect_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT article_collect_collect_id_fkey
    FOREIGN KEY (collect_id) REFERENCES public.collect(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.article_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  article_id bigint NOT NULL,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT article_history_user_article_key UNIQUE (user_id, article_id),
  CONSTRAINT article_history_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE,
  CONSTRAINT article_history_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.article_like (
  article_id bigint NOT NULL,
  user_id bigint NOT NULL,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  PRIMARY KEY (article_id, user_id),
  CONSTRAINT article_like_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT article_like_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.article_tag (
  article_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  PRIMARY KEY (article_id, tag_id),
  CONSTRAINT article_tag_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT article_tag_tag_id_fkey
    FOREIGN KEY (tag_id) REFERENCES public.tag(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.comment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  article_id bigint NOT NULL,
  comment_id bigint,
  reply_id bigint,
  content text NOT NULL CHECK (length(content) <= 1000),
  status integer DEFAULT 0,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT comment_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT comment_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT comment_comment_id_fkey
    FOREIGN KEY (comment_id) REFERENCES public.comment(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT comment_reply_id_fkey
    FOREIGN KEY (reply_id) REFERENCES public.comment(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.comment_like (
  comment_id bigint NOT NULL,
  user_id bigint NOT NULL,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  PRIMARY KEY (comment_id, user_id),
  CONSTRAINT comment_like_comment_id_fkey
    FOREIGN KEY (comment_id) REFERENCES public.comment(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT comment_like_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.file (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  article_id bigint,
  filename text NOT NULL CHECK (length(filename) <= 100),
  mimetype text CHECK (length(mimetype) <= 30),
  size integer,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  file_type text DEFAULT 'image' CHECK (file_type IN ('image', 'video')),
  CONSTRAINT file_filename_key UNIQUE (filename),
  CONSTRAINT file_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT file_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.image_meta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id bigint NOT NULL,
  is_cover boolean DEFAULT false,
  width integer,
  height integer,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT image_meta_file_id_key UNIQUE (file_id),
  CONSTRAINT image_meta_file_id_fkey
    FOREIGN KEY (file_id) REFERENCES public.file(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.report (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  article_id bigint,
  comment_id bigint,
  content text CHECK (length(content) <= 100),
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT report_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT report_article_id_fkey
    FOREIGN KEY (article_id) REFERENCES public.article(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT report_comment_id_fkey
    FOREIGN KEY (comment_id) REFERENCES public.comment(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.user_follow (
  user_id bigint NOT NULL,
  follower_id bigint NOT NULL,
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, follower_id),
  CONSTRAINT user_follow_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT user_follow_follower_id_fkey
    FOREIGN KEY (follower_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.video_meta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id bigint NOT NULL,
  poster text CHECK (length(poster) <= 255),
  duration integer,
  width integer,
  height integer,
  bitrate integer,
  format text CHECK (length(format) <= 20),
  transcode_status text DEFAULT 'pending'
    CHECK (transcode_status IN ('pending', 'processing', 'completed', 'failed')),
  create_at timestamptz DEFAULT now(),
  update_at timestamptz DEFAULT now(),
  CONSTRAINT video_meta_file_id_key UNIQUE (file_id),
  CONSTRAINT video_meta_file_id_fkey
    FOREIGN KEY (file_id) REFERENCES public.file(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------------
-- 表与字段注释（PostgreSQL 使用 COMMENT ON，语义对齐原 MySQL 业务含义）
-- ---------------------------------------------------------------------------

COMMENT ON TABLE public."user" IS '用户表，存储用户信息';
COMMENT ON COLUMN public."user".id IS '主键 ID';
COMMENT ON COLUMN public."user".name IS '用户名';
COMMENT ON COLUMN public."user".password IS '密码哈希，可为空（如仅 OAuth 登录）';
COMMENT ON COLUMN public."user".status IS '用户状态';
COMMENT ON COLUMN public."user".create_at IS '创建时间';
COMMENT ON COLUMN public."user".update_at IS '更新时间';
COMMENT ON COLUMN public."user".google_id IS 'Google OAuth 用户标识';
COMMENT ON COLUMN public."user".oauth_provider IS 'OAuth 提供方名称';
COMMENT ON COLUMN public."user".github_id IS 'GitHub OAuth 用户标识';

COMMENT ON TABLE public.tag IS '标签表，用于存储文章的标签信息';
COMMENT ON COLUMN public.tag.id IS '主键 ID';
COMMENT ON COLUMN public.tag.name IS '标签名称';
COMMENT ON COLUMN public.tag.create_at IS '创建时间';
COMMENT ON COLUMN public.tag.update_at IS '更新时间';

COMMENT ON TABLE public.article IS '文章表，存储用户发布的文章';
COMMENT ON COLUMN public.article.id IS '主键 ID';
COMMENT ON COLUMN public.article.user_id IS '作者用户 ID';
COMMENT ON COLUMN public.article.title IS '文章标题';
COMMENT ON COLUMN public.article.content IS '文章正文（HTML/Markdown）';
COMMENT ON COLUMN public.article.views IS '浏览次数';
COMMENT ON COLUMN public.article.status IS '文章状态';
COMMENT ON COLUMN public.article.create_at IS '创建时间';
COMMENT ON COLUMN public.article.update_at IS '更新时间';

COMMENT ON TABLE public.collect IS '收藏夹表，存储用户的收藏夹';
COMMENT ON COLUMN public.collect.id IS '主键 ID';
COMMENT ON COLUMN public.collect.user_id IS '所属用户 ID';
COMMENT ON COLUMN public.collect.name IS '收藏夹名称';
COMMENT ON COLUMN public.collect.create_at IS '创建时间';
COMMENT ON COLUMN public.collect.update_at IS '更新时间';

COMMENT ON TABLE public.avatar IS '头像表，存储用户的头像文件信息';
COMMENT ON COLUMN public.avatar.id IS '主键 ID';
COMMENT ON COLUMN public.avatar.user_id IS '用户 ID，可为空';
COMMENT ON COLUMN public.avatar.filename IS '头像文件名';
COMMENT ON COLUMN public.avatar.mimetype IS 'MIME 类型';
COMMENT ON COLUMN public.avatar.size IS '文件大小（字节）';
COMMENT ON COLUMN public.avatar.create_at IS '创建时间';
COMMENT ON COLUMN public.avatar.update_at IS '更新时间';

COMMENT ON TABLE public.profile IS '用户资料表，存储用户的详细资料';
COMMENT ON COLUMN public.profile.id IS '主键 ID';
COMMENT ON COLUMN public.profile.user_id IS '用户 ID，一对一关联';
COMMENT ON COLUMN public.profile.avatar_url IS '头像访问 URL';
COMMENT ON COLUMN public.profile.age IS '年龄';
COMMENT ON COLUMN public.profile.sex IS '性别';
COMMENT ON COLUMN public.profile.phone IS '电话';
COMMENT ON COLUMN public.profile.email IS '邮箱';
COMMENT ON COLUMN public.profile.career IS '职业';
COMMENT ON COLUMN public.profile.address IS '地址';
COMMENT ON COLUMN public.profile.sign IS '个性签名';
COMMENT ON COLUMN public.profile.create_at IS '创建时间';
COMMENT ON COLUMN public.profile.update_at IS '更新时间';

COMMENT ON TABLE public.article_collect IS '文章收藏关联表，关联文章与收藏夹的多对多关系';
COMMENT ON COLUMN public.article_collect.article_id IS '文章 ID';
COMMENT ON COLUMN public.article_collect.collect_id IS '收藏夹 ID';
COMMENT ON COLUMN public.article_collect.create_at IS '创建时间';
COMMENT ON COLUMN public.article_collect.update_at IS '更新时间';

COMMENT ON TABLE public.article_history IS '文章浏览历史，记录用户查看文章的历史';
COMMENT ON COLUMN public.article_history.id IS '主键 ID';
COMMENT ON COLUMN public.article_history.user_id IS '用户 ID';
COMMENT ON COLUMN public.article_history.article_id IS '文章 ID';
COMMENT ON COLUMN public.article_history.create_at IS '首次浏览时间';
COMMENT ON COLUMN public.article_history.update_at IS '最近浏览时间';

COMMENT ON TABLE public.article_like IS '文章点赞表，记录用户对文章的点赞';
COMMENT ON COLUMN public.article_like.article_id IS '文章 ID';
COMMENT ON COLUMN public.article_like.user_id IS '用户 ID';
COMMENT ON COLUMN public.article_like.create_at IS '创建时间';
COMMENT ON COLUMN public.article_like.update_at IS '更新时间';

COMMENT ON TABLE public.article_tag IS '文章标签关联表，关联文章与标签的多对多关系';
COMMENT ON COLUMN public.article_tag.article_id IS '文章 ID';
COMMENT ON COLUMN public.article_tag.tag_id IS '标签 ID';
COMMENT ON COLUMN public.article_tag.create_at IS '创建时间';
COMMENT ON COLUMN public.article_tag.update_at IS '更新时间';

COMMENT ON TABLE public.comment IS '评论表，存储文章的评论信息';
COMMENT ON COLUMN public.comment.id IS '主键 ID';
COMMENT ON COLUMN public.comment.user_id IS '评论用户 ID';
COMMENT ON COLUMN public.comment.article_id IS '所属文章 ID';
COMMENT ON COLUMN public.comment.comment_id IS '父评论 ID，一级评论为空';
COMMENT ON COLUMN public.comment.reply_id IS '被回复的评论 ID';
COMMENT ON COLUMN public.comment.content IS '评论内容';
COMMENT ON COLUMN public.comment.status IS '评论状态';
COMMENT ON COLUMN public.comment.create_at IS '创建时间';
COMMENT ON COLUMN public.comment.update_at IS '更新时间';

COMMENT ON TABLE public.comment_like IS '评论点赞表，记录用户对评论的点赞';
COMMENT ON COLUMN public.comment_like.comment_id IS '评论 ID';
COMMENT ON COLUMN public.comment_like.user_id IS '用户 ID';
COMMENT ON COLUMN public.comment_like.create_at IS '创建时间';
COMMENT ON COLUMN public.comment_like.update_at IS '更新时间';

COMMENT ON TABLE public.file IS '文件表，存储上传的文件信息';
COMMENT ON COLUMN public.file.id IS '主键 ID';
COMMENT ON COLUMN public.file.user_id IS '上传用户 ID，可为空';
COMMENT ON COLUMN public.file.article_id IS '关联文章 ID，可为空（如孤儿文件）';
COMMENT ON COLUMN public.file.filename IS '文件名';
COMMENT ON COLUMN public.file.mimetype IS 'MIME 类型';
COMMENT ON COLUMN public.file.size IS '文件大小（字节）';
COMMENT ON COLUMN public.file.create_at IS '创建时间';
COMMENT ON COLUMN public.file.update_at IS '更新时间';
COMMENT ON COLUMN public.file.file_type IS '文件类型：image 图片，video 视频';

COMMENT ON TABLE public.image_meta IS '图片文件元数据扩展表';
COMMENT ON COLUMN public.image_meta.id IS '主键 ID';
COMMENT ON COLUMN public.image_meta.file_id IS '关联的文件 ID';
COMMENT ON COLUMN public.image_meta.is_cover IS '是否为文章封面';
COMMENT ON COLUMN public.image_meta.width IS '图片宽度（像素）';
COMMENT ON COLUMN public.image_meta.height IS '图片高度（像素）';
COMMENT ON COLUMN public.image_meta.create_at IS '创建时间';
COMMENT ON COLUMN public.image_meta.update_at IS '更新时间';

COMMENT ON TABLE public.report IS '举报表，存储用户举报信息';
COMMENT ON COLUMN public.report.id IS '主键 ID';
COMMENT ON COLUMN public.report.user_id IS '举报用户 ID';
COMMENT ON COLUMN public.report.article_id IS '被举报文章 ID，可为空';
COMMENT ON COLUMN public.report.comment_id IS '被举报评论 ID，可为空';
COMMENT ON COLUMN public.report.content IS '举报说明';
COMMENT ON COLUMN public.report.create_at IS '创建时间';
COMMENT ON COLUMN public.report.update_at IS '更新时间';

COMMENT ON TABLE public.user_follow IS '用户关注表，记录用户之间的关注关系';
COMMENT ON COLUMN public.user_follow.user_id IS '被关注用户 ID';
COMMENT ON COLUMN public.user_follow.follower_id IS '关注者用户 ID';
COMMENT ON COLUMN public.user_follow.create_at IS '创建时间';
COMMENT ON COLUMN public.user_follow.update_at IS '更新时间';

COMMENT ON TABLE public.video_meta IS '视频文件元数据扩展表';
COMMENT ON COLUMN public.video_meta.id IS '主键 ID';
COMMENT ON COLUMN public.video_meta.file_id IS '关联的文件 ID';
COMMENT ON COLUMN public.video_meta.poster IS '视频封面图文件名';
COMMENT ON COLUMN public.video_meta.duration IS '视频时长（秒）';
COMMENT ON COLUMN public.video_meta.width IS '视频宽度（像素）';
COMMENT ON COLUMN public.video_meta.height IS '视频高度（像素）';
COMMENT ON COLUMN public.video_meta.bitrate IS '视频码率（kbps）';
COMMENT ON COLUMN public.video_meta.format IS '视频格式（如 mp4、webm）';
COMMENT ON COLUMN public.video_meta.transcode_status IS '转码状态：pending/processing/completed/failed';
COMMENT ON COLUMN public.video_meta.create_at IS '创建时间';
COMMENT ON COLUMN public.video_meta.update_at IS '更新时间';

COMMIT;
